{
 "title": "Consul Cluster Health",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": "show tag values on telegraf from cpu with key = \"host\" where role = 'consul-server'"
   },
   {
    "name": "dc",
    "label": "Datacenter",
    "query": "show tag values on telegraf from cpu with key = \"datacenter\" where role = 'consul-server'"
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "consul_autopilot_healthy",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    }
   ]
  },
  {
   "title": "Leader Last Contact",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consul_raft_leader_lastContact",
     "query": "SELECT max(\"upper\") AS \"upper\" FROM \"telegraf\".\"autogen\".\"consul_raft_leader_lastContact\" WHERE $timeFilter AND \"role\"='consul-server' GROUP BY time($__interval) FILL(0)",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT max(\"usage_user\") AS \"user_cpu\", max(\"usage_iowait\") AS \"iowait_cpu\" FROM \"autogen\".\"cpu\" WHERE \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^$dc$/  AND (\"role\" = 'consul-server') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "consul-server" }
     ]
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "diskio",
     "query": "SELECT non_negative_difference(max(\"read_bytes\")) + non_negative_difference(max(\"write_bytes\")) AS \"disk\" FROM \"autogen\".\"diskio\" WHERE \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^$dc$/  AND (\"role\" = 'consul-server') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "read_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "consul-server" }
     ]
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "query": "SELECT non_negative_difference(max(\"bytes_recv\")) + non_negative_difference(max(\"bytes_sent\")) AS \"bytes\" FROM \"autogen\".\"net\" WHERE \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^$dc$/  AND (\"role\" = 'consul-server') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "bytes_recv" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "consul-server" }
     ]
    }
   ]
  },
  {
   "title": "Server Count",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(tot) FROM (SELECT max(\"uptime\") AS \"tot\" FROM \"telegraf\".\"autogen\".\"system\" WHERE $timeFilter AND \"role\"='consul-server' GROUP BY \"host\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "RPC Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 14, "x": 3, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"value\") AS \"count\" FROM \"telegraf\".\"autogen\".\"consul_rpc_request\" WHERE \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^$dc$/  AND $timeFilter AND \"role\"='consul-server' GROUP BY time($__interval), \"host\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Runtime Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") AS \"alloc_bytes\" FROM \"telegraf\".\"autogen\".\"consul_runtime_alloc_bytes\" WHERE \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^$dc$/  AND $timeFilter AND \"role\"='consul-server' GROUP BY time($__interval), \"host\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT max(\"value\") AS \"sys_bytes\" FROM \"telegraf\".\"autogen\".\"consul_runtime_sys_bytes\" WHERE \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^$dc$/  AND $timeFilter AND \"role\"='consul-server' GROUP BY time($__interval), \"host\" FILL(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "query": "SELECT max(\"total\") AS \"total_bytes\" FROM \"mem\" WHERE (\"host\" =~ /^$host$/ AND \"datacenter\" =~ /^$dc$/ AND \"role\" = 'consul-server') AND $timeFilter GROUP BY time($__interval), \"host\" fill(null)",
     "select": [
      [
       { "params": [ "total" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "datacenter", "operator": "=~", "value": "/^$dc$/" },
      { "condition": "AND", "key": "role", "operator": "=", "value": "consul-server" }
     ]
    }
   ]
  },
  {
   "title": "Raft Transactions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") AS \"count\" FROM \"telegraf\".\"autogen\".\"consul_raft_apply\" WHERE \"datacenter\" =~ /^$dc$/  AND $timeFilter AND \"role\"='consul-server' GROUP BY time($__interval) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "consul_raft_commitTime",
     "query": "SELECT max(\"value\") AS \"commit_time_ms\" FROM \"autogen\".\"consul_raft_commitTime\" WHERE (\"role\" = 'consul-server') AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "role", "operator": "=", "value": "consul-server" },
      { "condition": "AND", "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Commit Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consul_txn_apply",
     "query": "SELECT mean(\"mean\") AS \"mean\", max(\"90_percentile\") AS \"90_percentile\" FROM \"telegraf\".\"autogen\".\"consul_raft_commitTime\" WHERE $timeFilter AND \"role\"='consul-server' GROUP BY time($__interval) FILL(null)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consul_txn_apply",
     "query": "SELECT mean(\"mean\") AS \"mean\", max(\"90_percentile\") AS \"90_percentile\" FROM \"telegraf\".\"autogen\".\"consul_raft_commitTime\" WHERE $timeFilter AND \"role\"='consul-server' GROUP BY time($__interval) FILL(null)",
     "select": [
      [
       { "params": [ "upper" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "consul_txn_apply",
     "query": "SELECT mean(\"mean\") AS \"mean\", max(\"90_percentile\") AS \"90_percentile\" FROM \"telegraf\".\"autogen\".\"consul_raft_commitTime\" WHERE $timeFilter AND \"role\"='consul-server' GROUP BY time($__interval) FILL(null)",
     "select": [
      [
       { "params": [ "lower" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"upper\")/1000000 AS \"milliseconds\" FROM \"telegraf\".\"autogen\".\"consul_runtime_gc_pause_ns\" WHERE \"host\" =~ /^$host$/ AND \"datacenter\" =~ /^$dc$/  AND $timeFilter AND \"role\"='consul-server' GROUP BY host, time($__interval) FILL(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "KV Writes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "consul_kvs_apply",
     "query": "SELECT mean(\"count\") AS count FROM \"autogen\".\"consul_kvs_apply\" WHERE (\"datacenter\" =~ /^$dc$/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "consul_kvs_apply",
     "query": "SELECT mean(\"mean\") AS time_ms FROM \"autogen\".\"consul_kvs_apply\" WHERE (\"datacenter\" =~ /^$dc$/) AND $timeFilter GROUP BY time($__interval) fill(0)",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    }
   ]
  },
  {
   "title": "RPC Requests By Client",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "consul_client_rpc",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    }
   ]
  },
  {
   "title": "Election Attempts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "consul_raft_state_candidate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    }
   ]
  },
  {
   "title": "Leadership Changes",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 15 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "consul_raft_state_leader",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "datacenter", "operator": "=~", "value": "/^$dc$/" }
     ]
    }
   ]
  }
 ]
}